@REM
@REM
@REM
@REM
CHCP 65001
@SET LC_ALL=ko_KR.UTF-8
@REM
@REM
@REM
@REM
@SET PROJECT=resource3d
@SET OPENSCAD_PROJECT=epaper
@SET HOME_DIR=%CURRENT_PATH%
@SET ECLIPSE_WORKSPACE_DIR=C:/src/eclipse-workspace
@SET PROJECT_DIR=%ECLIPSE_WORKSPACE_DIR%/%PROJECT%
@SET SOURCE_DIR=%PROJECT_DIR%/openscad/src/%OPENSCAD_PROJECT%
@SET DEPLOY_DIR=%SOURCE_DIR%
@SET OPENSCAD=C:\apps\openscad-2021.01\openscad.com
@SET SOURCE_SCAD=%OPENSCAD_PROJECT%.scad
@SET DEFAULT_OPTION=--export-format asciistl
@REM
@REM
@REM
@REM
DATE /t
TIME /t
ECHO %CURRENT_PATH% %CURRENT_FILENAME% %OPENSCAD% %SOURCE_SCAD%
@REM
@REM
@REM
@REM
%OPENSCAD% %DEFAULT_OPTION% -D command=1 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-prototype-8x16-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
