#!/bin/bash
#
#
#
PROJECT=resource3d
OPENSCAD_PROJECT=parking
HOME_DIR=/home/andold
ECLIPSE_WORKSPACE_DIR=$HOME_DIR/src/eclipse-workspace
PROJECT_DIR=$ECLIPSE_WORKSPACE_DIR/$PROJECT
SOURCE_DIR=$PROJECT_DIR/openscad/src/$OPENSCAD_PROJECT
DEPLOY_DIR=/media/owl/data/$PROJECT/stl
OPENSCAD=/usr/bin/openscad
SOURCE_SCAD=$SOURCE_DIR/$OPENSCAD_PROJECT.scad
DEFAULT_OPTION="--export-format asciistl"
#
#
#
#
date
echo $SOURCE_SCAD $DEPLOY_DIR
#
#
#
#
$OPENSCAD $DEFAULT_OPTION -D command=-1 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-test.stl" $SOURCE_SCAD
$OPENSCAD $DEFAULT_OPTION -D command=1 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-pyskkh.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=2 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-kkhpys.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=3 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-lhc.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=4 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-jju.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=5 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-hjh.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=6 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-kej.stl" $SOURCE_SCAD &
$OPENSCAD $DEFAULT_OPTION -D command=7 -o "$DEPLOY_DIR/$OPENSCAD_PROJECT-shs.stl" $SOURCE_SCAD &
