@REM
@REM
@REM
@REM
CHCP 65001
@SET LC_ALL=ko_KR.UTF-8
@REM
@REM
@REM
@REM
@SET PROJECT=resource3d
@SET OPENSCAD_PROJECT=parking
@SET HOME_DIR=%CURRENT_PATH%
@SET ECLIPSE_WORKSPACE_DIR=C:/src/eclipse-workspace
@SET PROJECT_DIR=%ECLIPSE_WORKSPACE_DIR%/%PROJECT%
@SET SOURCE_DIR=%PROJECT_DIR%/openscad/src/%OPENSCAD_PROJECT%
@SET DEPLOY_DIR=%SOURCE_DIR%
@SET OPENSCAD=C:\apps\openscad-2021.01\openscad.com
@SET SOURCE_SCAD=%OPENSCAD_PROJECT%.scad
@SET DEFAULT_OPTION=--export-format asciistl
@REM
@REM
@REM
@REM
DATE /t
TIME /t
ECHO %CURRENT_PATH% %CURRENT_FILENAME% %OPENSCAD% %SOURCE_SCAD%
@REM
@REM
@REM
@REM
REM %OPENSCAD% %DEFAULT_OPTION% -D command=-1 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-test.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=1 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-pyskkh.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=2 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-kkhpys.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=3 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-lhc.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=4 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-jju.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=5 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-hjh.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=6 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-kej.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=7 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-shs.stl" %SOURCE_SCAD%

REM %OPENSCAD% %DEFAULT_OPTION% -D command=8 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-51131208-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=9 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-36539094-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=10 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-26523464-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=11 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-40246352-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=12 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-36896617-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=13 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-36380990-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=14 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-57058849-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=15 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-53838849-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=16 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-38756082-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=17 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-32490190-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=18 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-5705884953838849-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
REM %OPENSCAD% %DEFAULT_OPTION% -D command=19 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-3875608232490190-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%

%OPENSCAD% %DEFAULT_OPTION% -D command=20 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-5113120836539094-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=21 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-2652346440246352-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=22 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-3689661736380990-%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%.stl" %SOURCE_SCAD%
