@REM
@REM
@REM
@REM
CHCP 65001
@SET LC_ALL=ko_KR.UTF-8
@REM
@REM
@REM
@REM
@SET PROJECT=resource3d
@SET OPENSCAD_PROJECT=parking
@SET HOME_DIR=%CURRENT_PATH%
@SET ECLIPSE_WORKSPACE_DIR=C:/src/eclipse-workspace
@SET PROJECT_DIR=%ECLIPSE_WORKSPACE_DIR%/%PROJECT%
@SET SOURCE_DIR=%PROJECT_DIR%/openscad/src/%OPENSCAD_PROJECT%
@SET DEPLOY_DIR=W:/data/%PROJECT%/stl
@SET OPENSCAD=C:\apps\openscad-2021.01\openscad.com
@SET SOURCE_SCAD=%OPENSCAD_PROJECT%.scad
@SET DEFAULT_OPTION=--export-format asciistl
@REM
@REM
@REM
@REM
DATE /t
TIME /t
ECHO %CURRENT_PATH% %CURRENT_FILENAME% %OPENSCAD% %SOURCE_SCAD%
@REM
@REM
@REM
@REM
%OPENSCAD% %DEFAULT_OPTION% -D command=-1 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-test.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=1 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-pyskkh.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=2 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-kkhpys.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=3 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-lhc.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=4 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-jju.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=5 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-hjh.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=6 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-kej.stl" %SOURCE_SCAD%
%OPENSCAD% %DEFAULT_OPTION% -D command=7 -o "%DEPLOY_DIR%/%OPENSCAD_PROJECT%-shs.stl" %SOURCE_SCAD%
